# values.yaml
postgresql:
  nameOverride: "postgres"
  image:
    repository: postgres
    tag: "14"
    pullPolicy: IfNotPresent
    containerPort: 5432
  
  tailscale:
    status: true
    
  secretRef: postgres-secrets

  replicaCount: 1
  
  service:
    type: NodePort
    port: 5432
    targetPort: 5432
  
  persistence:
    enabled: true
    storageClass: manual
    size: 20Gi
    accessMode: ReadWriteMany
    
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
