# templates/deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.nameOverride }}
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgresql.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.nameOverride }}
    spec:
      containers:
        - name: {{ .Values.postgresql.nameOverride }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgresql.image.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.nameOverride }}-secret
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.nameOverride }}-pvc
