# templates/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgresql.nameOverride }}-pv
  labels:
    app: {{ .Values.postgresql.nameOverride }}
spec:
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  hostPath:
    path: /data/postgresql