# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.nameOverride }}-pvc
  labels:
    app: {{ .Values.postgresql.nameOverride }}
spec:
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
