# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.nameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgresql.nameOverride }}
  annotations:
    {{- if eq .Values.postgresql.tailscale.status true }}
    tailscale.com/expose: "true"
    {{- end }}
spec:
  {{- if eq .Values.postgresql.tailscale.status true }}
  type: LoadBalancer
  {{- else }}
  type: {{ .Values.postgresql.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.postgresql.nameOverride }}