# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.nameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgresql.nameOverride }}
  annotations:
    {{- if eq .Values.postgresql.service.type "LoadBalancer" }}
    metallb.universe.tf/address-pool: tailscale
    {{- end }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.postgresql.nameOverride }}