# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.nameOverride }}
  labels:
    app: {{ .Values.postgresql.nameOverride }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
  selector:
    app: {{ .Values.postgresql.nameOverride }}